import type { Attributes, PlayerLink } from "@/lib/types";

function attrs(
  pace: number,
  shooting: number,
  passing: number,
  dribbling: number,
  defending: number,
  physical: number,
): Attributes {
  return { pace, shooting, passing, dribbling, defending, physical };
}

export const playerLinks: PlayerLink[] = [
  {
    id: "1",
    slug: "vinicius-jr",
    fieldVsGame:
      "No campo, o desequilíbrio vem da 1x1 e da profundidade. No FC, o overall alto às vezes esconde que o Vini real decide mais pela quebra de linha do que pelo chute de fora.",
    real: {
      id: "r1",
      name: "Vinícius Jr",
      club: "Real Madrid",
      position: "PE",
      season: "2025/26",
      goals: 18,
      assists: 14,
      attributes: attrs(96, 78, 76, 93, 32, 68),
    },
    ea: {
      id: "e1",
      name: "Vinícius Jr",
      club: "Real Madrid",
      overall: 90,
      position: "LW",
      archetype: "Inside Forward+",
      attributes: attrs(95, 80, 78, 91, 29, 70),
    },
  },
  {
    id: "2",
    slug: "haaland",
    fieldVsGame:
      "Haaland no gramado é gravidade na área. No jogo, o overall de 9 explora o sprint e o chute; o movimento de pinça do centroavante real ainda é mais cruel do que o timing da IA.",
    real: {
      id: "r2",
      name: "Erling Haaland",
      club: "Manchester City",
      position: "ATA",
      season: "2025/26",
      goals: 31,
      assists: 6,
      attributes: attrs(89, 94, 66, 72, 45, 88),
    },
    ea: {
      id: "e2",
      name: "Erling Haaland",
      club: "Manchester City",
      overall: 91,
      position: "ST",
      archetype: "Advanced Forward+",
      attributes: attrs(89, 93, 68, 74, 49, 88),
    },
  },
  {
    id: "3",
    slug: "bellingham",
    fieldVsGame:
      "Bellingham chega na área como um segundo atacante. O card no FC valoriza box-to-box; no campo, a leitura de espaço entre as linhas é o que o torna único.",
    real: {
      id: "r3",
      name: "Jude Bellingham",
      club: "Real Madrid",
      position: "MEI",
      season: "2025/26",
      goals: 16,
      assists: 10,
      attributes: attrs(82, 84, 83, 86, 76, 84),
    },
    ea: {
      id: "e3",
      name: "Jude Bellingham",
      club: "Real Madrid",
      overall: 90,
      position: "CAM",
      archetype: "Box-to-Box+",
      attributes: attrs(80, 83, 84, 87, 78, 83),
    },
  },
  {
    id: "4",
    slug: "mbappe",
    fieldVsGame:
      "Mbappé segue o perfil de velocidade pura. No pad, qualquer toque em sprint explode; no campo, a decisão de quando não correr é tão importante quanto o 36 km/h.",
    real: {
      id: "r4",
      name: "Kylian Mbappé",
      club: "Real Madrid",
      position: "ATA",
      season: "2025/26",
      goals: 34,
      assists: 9,
      attributes: attrs(97, 89, 80, 92, 36, 77),
    },
    ea: {
      id: "e4",
      name: "Kylian Mbappé",
      club: "Real Madrid",
      overall: 91,
      position: "ST",
      archetype: "Spearhead",
      attributes: attrs(97, 90, 81, 92, 39, 78),
    },
  },
  {
    id: "5",
    slug: "messi",
    fieldVsGame:
      "Messi no FC ainda dribbla em câmera lenta mágica. No campo, o volume caiu com a idade; a visão e o chute colocado continuam fora da escala do overall.",
    real: {
      id: "r5",
      name: "Lionel Messi",
      club: "Inter Miami",
      position: "SA",
      season: "2025",
      goals: 22,
      assists: 16,
      attributes: attrs(80, 90, 91, 94, 35, 64),
    },
    ea: {
      id: "e5",
      name: "Lionel Messi",
      club: "Inter Miami",
      overall: 88,
      position: "CAM",
      archetype: "Playmaker+",
      attributes: attrs(81, 88, 90, 93, 33, 65),
    },
  },
  {
    id: "6",
    slug: "cristiano-ronaldo",
    fieldVsGame:
      "CR7 no campo ainda vive do posicionamento e da cabeça. O card no FC costuma inflar o chute e o físico — o ritmo real já não é o de Madrid.",
    real: {
      id: "r6",
      name: "Cristiano Ronaldo",
      club: "Al-Nassr",
      position: "ATA",
      season: "2025/26",
      goals: 28,
      assists: 4,
      attributes: attrs(81, 92, 76, 80, 34, 77),
    },
    ea: {
      id: "e6",
      name: "Cristiano Ronaldo",
      club: "Al-Nassr",
      overall: 86,
      position: "ST",
      archetype: "Poacher",
      attributes: attrs(82, 91, 75, 81, 34, 78),
    },
  },
  {
    id: "7",
    slug: "de-bruyne",
    fieldVsGame:
      "De Bruyne no gramado é passe de 40 metros. No FC, o overall alto às vezes vira chute de fora; o melhor uso ainda é o through ball na diagonal.",
    real: {
      id: "r7",
      name: "Kevin De Bruyne",
      club: "Napoli",
      position: "MEI",
      season: "2025/26",
      goals: 8,
      assists: 12,
      attributes: attrs(72, 86, 93, 84, 62, 76),
    },
    ea: {
      id: "e7",
      name: "Kevin De Bruyne",
      club: "Napoli",
      overall: 88,
      position: "CAM",
      archetype: "Classic 10",
      attributes: attrs(70, 86, 93, 85, 61, 74),
    },
  },
  {
    id: "8",
    slug: "salah",
    fieldVsGame:
      "Salah corta para dentro e finaliza cedo. O card no FC premia o chute de pé esquerdo; no campo, a inteligência de quando atrasar o drible vale mais.",
    real: {
      id: "r8",
      name: "Mohamed Salah",
      club: "Liverpool",
      position: "PD",
      season: "2025/26",
      goals: 24,
      assists: 13,
      attributes: attrs(90, 88, 82, 87, 45, 75),
    },
    ea: {
      id: "e8",
      name: "Mohamed Salah",
      club: "Liverpool",
      overall: 89,
      position: "RW",
      archetype: "Inside Forward+",
      attributes: attrs(91, 87, 81, 88, 43, 76),
    },
  },
  {
    id: "9",
    slug: "rodri",
    fieldVsGame:
      "Rodri dita o ritmo com um toque. No FC, volantes 90 overall às vezes viram box-to-box demais — o Rodri real raramente entra na área.",
    real: {
      id: "r9",
      name: "Rodri",
      club: "Manchester City",
      position: "VOL",
      season: "2025/26",
      goals: 7,
      assists: 8,
      attributes: attrs(66, 74, 88, 80, 86, 84),
    },
    ea: {
      id: "e9",
      name: "Rodri",
      club: "Manchester City",
      overall: 91,
      position: "CDM",
      archetype: "Holding+",
      attributes: attrs(65, 73, 87, 81, 87, 85),
    },
  },
  {
    id: "10",
    slug: "lamine-yamal",
    fieldVsGame:
      "Yamal no campo é descaroço na ponta. O overall no FC ainda subestima a tomada de decisão; no pad, o dribbling já é absurdo.",
    real: {
      id: "r10",
      name: "Lamine Yamal",
      club: "Barcelona",
      position: "PD",
      season: "2025/26",
      goals: 14,
      assists: 17,
      attributes: attrs(91, 78, 82, 93, 28, 60),
    },
    ea: {
      id: "e10",
      name: "Lamine Yamal",
      club: "Barcelona",
      overall: 86,
      position: "RW",
      archetype: "Winger+",
      attributes: attrs(90, 77, 80, 91, 26, 62),
    },
  },
  {
    id: "11",
    slug: "saka",
    fieldVsGame:
      "Saka combina trabalho defensivo e 1x1. O card no FC às vezes vira só ponta ofensivo; no Arsenal, ele fecha o corredor inteiro.",
    real: {
      id: "r11",
      name: "Bukayo Saka",
      club: "Arsenal",
      position: "PD",
      season: "2025/26",
      goals: 15,
      assists: 12,
      attributes: attrs(88, 82, 81, 88, 58, 72),
    },
    ea: {
      id: "e11",
      name: "Bukayo Saka",
      club: "Arsenal",
      overall: 87,
      position: "RW",
      archetype: "Wide Playmaker",
      attributes: attrs(87, 81, 82, 87, 55, 73),
    },
  },
  {
    id: "12",
    slug: "kane",
    fieldVsGame:
      "Kane é 9 e 10 ao mesmo tempo. No FC, o overall de chute brilha; no campo, o passe de costas para o gol é o superpoder escondido.",
    real: {
      id: "r12",
      name: "Harry Kane",
      club: "Bayern de Munique",
      position: "ATA",
      season: "2025/26",
      goals: 29,
      assists: 11,
      attributes: attrs(74, 93, 86, 80, 48, 82),
    },
    ea: {
      id: "e12",
      name: "Harry Kane",
      club: "Bayern de Munique",
      overall: 90,
      position: "ST",
      archetype: "False 9",
      attributes: attrs(73, 92, 85, 81, 47, 83),
    },
  },
  {
    id: "13",
    slug: "van-dijk",
    fieldVsGame:
      "Van Dijk no campo ainda organiza a linha com a voz. No FC, zagueiros altos sofrem no giro — use-o para interceptar, não para correr nas costas.",
    real: {
      id: "r13",
      name: "Virgil van Dijk",
      club: "Liverpool",
      position: "ZAG",
      season: "2025/26",
      goals: 4,
      assists: 2,
      attributes: attrs(76, 58, 72, 70, 91, 86),
    },
    ea: {
      id: "e13",
      name: "Virgil van Dijk",
      club: "Liverpool",
      overall: 89,
      position: "CB",
      archetype: "Defender+",
      attributes: attrs(75, 60, 71, 68, 91, 87),
    },
  },
  {
    id: "14",
    slug: "courtois",
    fieldVsGame:
      "Courtois fecha o ângulo com o corpo. No FC, o overall de goleiro oscila mais que o rendimento real em noites de Champions.",
    real: {
      id: "r14",
      name: "Thibaut Courtois",
      club: "Real Madrid",
      position: "GOL",
      season: "2025/26",
      goals: 0,
      assists: 0,
      attributes: attrs(58, 25, 45, 40, 55, 86),
    },
    ea: {
      id: "e14",
      name: "Thibaut Courtois",
      club: "Real Madrid",
      overall: 89,
      position: "GK",
      archetype: "Sweeper Keeper",
      attributes: attrs(56, 22, 48, 42, 58, 88),
    },
  },
  {
    id: "15",
    slug: "wirtz",
    fieldVsGame:
      "Wirtz recebe entre as linhas e vira o jogo no primeiro toque. O card no FC já é meta; no campo, a coragem de receber de costas é o diferencial.",
    real: {
      id: "r15",
      name: "Florian Wirtz",
      club: "Liverpool",
      position: "MEI",
      season: "2025/26",
      goals: 12,
      assists: 14,
      attributes: attrs(84, 80, 86, 90, 52, 64),
    },
    ea: {
      id: "e15",
      name: "Florian Wirtz",
      club: "Liverpool",
      overall: 88,
      position: "CAM",
      archetype: "Shadow Striker",
      attributes: attrs(83, 81, 85, 89, 50, 63),
    },
  },
  {
    id: "16",
    slug: "palmer",
    fieldVsGame:
      "Palmer parece jogar sem pressa. No FC, o overall ainda tenta alcançar o impacto real no Chelsea: chute de média e passe mortal.",
    real: {
      id: "r16",
      name: "Cole Palmer",
      club: "Chelsea",
      position: "SA",
      season: "2025/26",
      goals: 18,
      assists: 11,
      attributes: attrs(82, 85, 84, 88, 46, 68),
    },
    ea: {
      id: "e16",
      name: "Cole Palmer",
      club: "Chelsea",
      overall: 86,
      position: "CAM",
      archetype: "Wide Playmaker",
      attributes: attrs(81, 84, 83, 87, 44, 67),
    },
  },
  {
    id: "17",
    slug: "pedri",
    fieldVsGame:
      "Pedri esconde a bola no meio. O FC às vezes pune o físico baixo; no campo, ele não precisa do físico — precisa de um toque a menos.",
    real: {
      id: "r17",
      name: "Pedri",
      club: "Barcelona",
      position: "MC",
      season: "2025/26",
      goals: 6,
      assists: 9,
      attributes: attrs(78, 72, 88, 90, 64, 62),
    },
    ea: {
      id: "e17",
      name: "Pedri",
      club: "Barcelona",
      overall: 87,
      position: "CM",
      archetype: "Orchestrator",
      attributes: attrs(77, 71, 87, 89, 63, 61),
    },
  },
  {
    id: "18",
    slug: "lewandowski",
    fieldVsGame:
      "Lewandowski segue o 9 de área. No FC, o ritmo caiu; no campo, o timing de ataque à bola continua de elite.",
    real: {
      id: "r18",
      name: "Robert Lewandowski",
      club: "Barcelona",
      position: "ATA",
      season: "2025/26",
      goals: 23,
      assists: 5,
      attributes: attrs(74, 91, 75, 78, 42, 80),
    },
    ea: {
      id: "e18",
      name: "Robert Lewandowski",
      club: "Barcelona",
      overall: 88,
      position: "ST",
      archetype: "Poacher+",
      attributes: attrs(73, 90, 74, 77, 41, 81),
    },
  },
  {
    id: "19",
    slug: "dembele",
    fieldVsGame:
      "Dembélé no PSG virou protagonista. No FC, o 5 estrela de perna ruim é o brinquedo; no campo, o cruzamento atrasado é a arma nova.",
    real: {
      id: "r19",
      name: "Ousmane Dembélé",
      club: "PSG",
      position: "SA",
      season: "2025/26",
      goals: 21,
      assists: 15,
      attributes: attrs(93, 82, 80, 91, 38, 66),
    },
    ea: {
      id: "e19",
      name: "Ousmane Dembélé",
      club: "PSG",
      overall: 87,
      position: "RW",
      archetype: "Trickster+",
      attributes: attrs(94, 81, 79, 90, 36, 65),
    },
  },
  {
    id: "20",
    slug: "valverde",
    fieldVsGame:
      "Valverde cobre 12 km e ainda chuta de fora. O card no FC é box-to-box perfeito; no campo, a função às vezes é de terceiro zagueiro na transição.",
    real: {
      id: "r20",
      name: "Federico Valverde",
      club: "Real Madrid",
      position: "MC",
      season: "2025/26",
      goals: 9,
      assists: 8,
      attributes: attrs(88, 80, 82, 81, 80, 85),
    },
    ea: {
      id: "e20",
      name: "Federico Valverde",
      club: "Real Madrid",
      overall: 88,
      position: "CM",
      archetype: "Box-to-Box+",
      attributes: attrs(87, 79, 81, 80, 81, 86),
    },
  },
  {
    id: "21",
    slug: "musiala",
    fieldVsGame:
      "Musiala dribla em espaço nenhum. No FC, o dribbling 90 é justo; no campo, a recepção no meio-espaço é o que o Guardiola mais cobiçava.",
    real: {
      id: "r21",
      name: "Jamal Musiala",
      club: "Bayern de Munique",
      position: "MEI",
      season: "2025/26",
      goals: 14,
      assists: 10,
      attributes: attrs(86, 81, 80, 92, 48, 64),
    },
    ea: {
      id: "e21",
      name: "Jamal Musiala",
      club: "Bayern de Munique",
      overall: 87,
      position: "CAM",
      archetype: "Inside Forward",
      attributes: attrs(85, 80, 79, 91, 46, 63),
    },
  },
  {
    id: "22",
    slug: "isak",
    fieldVsGame:
      "Isak combina 9 clássico e ponta. O overall no FC subiu rápido; no campo, a finalização em corrida já era de seleção.",
    real: {
      id: "r22",
      name: "Alexander Isak",
      club: "Liverpool",
      position: "ATA",
      season: "2025/26",
      goals: 22,
      assists: 6,
      attributes: attrs(88, 86, 72, 84, 40, 78),
    },
    ea: {
      id: "e22",
      name: "Alexander Isak",
      club: "Liverpool",
      overall: 87,
      position: "ST",
      archetype: "Advanced Forward",
      attributes: attrs(87, 85, 71, 83, 38, 77),
    },
  },
  {
    id: "23",
    slug: "rodrygo",
    fieldVsGame:
      "Rodrygo explode em noites grandes. O FC costuma deixá-lo um degrau abaixo do Vini; no campo, o primeiro gol em clássico é especialidade da casa.",
    real: {
      id: "r23",
      name: "Rodrygo",
      club: "Real Madrid",
      position: "PD",
      season: "2025/26",
      goals: 17,
      assists: 9,
      attributes: attrs(91, 82, 78, 89, 36, 66),
    },
    ea: {
      id: "e23",
      name: "Rodrygo",
      club: "Real Madrid",
      overall: 86,
      position: "RW",
      archetype: "Inside Forward",
      attributes: attrs(90, 81, 77, 88, 34, 65),
    },
  },
  {
    id: "24",
    slug: "bruno-fernandes",
    fieldVsGame:
      "Bruno arrisca o passe que ninguém vê. No FC, o overall de visão é alto; no campo, o volume de chances criadas ainda é absurdo mesmo quando o United oscila.",
    real: {
      id: "r24",
      name: "Bruno Fernandes",
      club: "Manchester United",
      position: "MEI",
      season: "2025/26",
      goals: 12,
      assists: 13,
      attributes: attrs(76, 84, 90, 83, 62, 74),
    },
    ea: {
      id: "e24",
      name: "Bruno Fernandes",
      club: "Manchester United",
      overall: 87,
      position: "CAM",
      archetype: "Classic 10+",
      attributes: attrs(75, 83, 89, 82, 60, 73),
    },
  },
];
